openapi: 3.0.3
info:
  title: SpokeToWork Company Tracking API
  description: |
    API for managing private companies in SpokeToWork.
    All endpoints require authentication via Supabase Auth.
    Implemented via Supabase client library (not REST endpoints).
  version: 1.0.0

paths:
  /companies:
    get:
      summary: List user's companies
      description: Returns all companies for the authenticated user
      parameters:
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/ApplicationStatus'
          description: Filter by application status
        - name: sort
          in: query
          schema:
            type: string
            enum: [name, distance, priority, status, created_at]
            default: created_at
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: List of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
        '401':
          description: Not authenticated

    post:
      summary: Create a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyCreate'
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Validation error
        '401':
          description: Not authenticated

  /companies/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get a company by ID
      responses:
        '200':
          description: Company details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '404':
          description: Company not found

    patch:
      summary: Update a company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyUpdate'
      responses:
        '200':
          description: Company updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Validation error
        '404':
          description: Company not found

    delete:
      summary: Delete a company
      responses:
        '204':
          description: Company deleted
        '404':
          description: Company not found

  /home-location:
    get:
      summary: Get user's home location
      responses:
        '200':
          description: Home location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomeLocation'
        '404':
          description: Home location not set

    put:
      summary: Set or update home location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomeLocationUpdate'
      responses:
        '200':
          description: Home location updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomeLocation'
        '400':
          description: Validation error

  /geocode:
    get:
      summary: Geocode an address
      description: Converts address to coordinates via Nominatim
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Geocoding result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeocodingResult'
        '404':
          description: Address not found

components:
  schemas:
    ApplicationStatus:
      type: string
      enum:
        - not_applied
        - applied
        - screening
        - interviewing
        - offer
        - closed

    Company:
      type: object
      required:
        - id
        - name
        - address
        - lat
        - lng
        - status
        - priority
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 200
        address:
          type: string
          maxLength: 500
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        contact_name:
          type: string
          maxLength: 200
          nullable: true
        contact_email:
          type: string
          format: email
          nullable: true
        contact_phone:
          type: string
          maxLength: 20
          nullable: true
        notes:
          type: string
          maxLength: 2000
          nullable: true
        status:
          $ref: '#/components/schemas/ApplicationStatus'
        priority:
          type: integer
          minimum: 1
          maximum: 5
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        distance_miles:
          type: number
          format: double
          description: Calculated distance from home (not stored)

    CompanyCreate:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          maxLength: 200
        address:
          type: string
          maxLength: 500
        contact_name:
          type: string
          maxLength: 200
        contact_email:
          type: string
          format: email
        contact_phone:
          type: string
          maxLength: 20
        notes:
          type: string
          maxLength: 2000
        priority:
          type: integer
          minimum: 1
          maximum: 5
          default: 3

    CompanyUpdate:
      type: object
      properties:
        name:
          type: string
          maxLength: 200
        address:
          type: string
          maxLength: 500
        contact_name:
          type: string
          maxLength: 200
          nullable: true
        contact_email:
          type: string
          format: email
          nullable: true
        contact_phone:
          type: string
          maxLength: 20
          nullable: true
        notes:
          type: string
          maxLength: 2000
          nullable: true
        status:
          $ref: '#/components/schemas/ApplicationStatus'
        priority:
          type: integer
          minimum: 1
          maximum: 5

    HomeLocation:
      type: object
      required:
        - address
        - lat
        - lng
        - updated_at
      properties:
        address:
          type: string
          maxLength: 500
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        updated_at:
          type: string
          format: date-time

    HomeLocationUpdate:
      type: object
      required:
        - address
      properties:
        address:
          type: string
          maxLength: 500

    GeocodingResult:
      type: object
      required:
        - lat
        - lng
        - display_name
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        display_name:
          type: string
          description: Formatted address from geocoder
